// Code generated by "stringer -type CosmosCLA"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[claGetVersion-0]
	_ = x[claSignSecp256K1-2]
	_ = x[claGetAddrSecp256K1-4]
}

const (
	_CosmosCLA_name_0 = "claGetVersion"
	_CosmosCLA_name_1 = "claSignSecp256K1"
	_CosmosCLA_name_2 = "claGetAddrSecp256K1"
)

func (i CosmosCLA) String() string {
	switch {
	case i == 0:
		return _CosmosCLA_name_0
	case i == 2:
		return _CosmosCLA_name_1
	case i == 4:
		return _CosmosCLA_name_2
	default:
		return "CosmosCLA(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
