// Code generated by "stringer -type command"; DO NOT EDIT.

package cosmos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[claGetVersion-0]
	_ = x[claSignSecp256K1-2]
	_ = x[claGetAddrSecp256K1-4]
}

const (
	_command_name_0 = "claGetVersion"
	_command_name_1 = "claSignSecp256K1"
	_command_name_2 = "claGetAddrSecp256K1"
)

func (i command) String() string {
	switch {
	case i == 0:
		return _command_name_0
	case i == 2:
		return _command_name_1
	case i == 4:
		return _command_name_2
	default:
		return "command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
