// Code generated by "stringer -type signPayloadDescr"; DO NOT EDIT.

package cosmos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[signInit-0]
	_ = x[signAdd-1]
	_ = x[signLast-2]
}

const _signPayloadDescr_name = "signInitsignAddsignLast"

var _signPayloadDescr_index = [...]uint8{0, 8, 15, 23}

func (i signPayloadDescr) String() string {
	if i >= signPayloadDescr(len(_signPayloadDescr_index)-1) {
		return "signPayloadDescr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _signPayloadDescr_name[_signPayloadDescr_index[i]:_signPayloadDescr_index[i+1]]
}
