// Code generated by "stringer -type=Algorithm"; DO NOT EDIT.

package crypto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlgoSecp256K1-0]
}

const _Algorithm_name = "AlgoSecp256K1"

var _Algorithm_index = [...]uint8{0, 13}

func (i Algorithm) String() string {
	if i >= Algorithm(len(_Algorithm_index)-1) {
		return "Algorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Algorithm_name[_Algorithm_index[i]:_Algorithm_index[i+1]]
}
